import { createContext, useContext, useState, type ReactNode } from 'react'
import { Link, useNavigate, useRouterState } from '@tanstack/react-router'
import { ArrowRight, Check, ChevronDown, CircleHelp, Heart, MapPin, Package, Search, ShoppingCart, Star, Store, UserRound, X, Plus, Minus, Trash2, ShieldCheck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { products, shops, formatMoney, cartTotals, type CartItem, type Product } from '@/lib/catalog'

type MarketState = { cart: CartItem[]; favorites: string[]; add: (product: Product, quantity?: number, size?: string, color?: string) => void; toggle: (id: string) => void; update: (index: number, quantity: number) => void; remove: (index: number) => void; openProduct: (product: Product) => void; notify: (text: string) => void }
const MarketContext = createContext<MarketState | null>(null)
export function useMarket() { const value = useContext(MarketContext); if (!value) throw new Error('Marketplace provider missing'); return value }
export function Brand() { return <span className="brand"><span className="brand-main">TOUT<span className="brand-infinity">∞</span>SUITE</span><span className="brand-sub">ANNONCES</span></span> }
export function MarketplaceProvider({ children }: { children: ReactNode }) {
  const [cart, setCart] = useState<CartItem[]>([])
  const [favorites, setFavorites] = useState<string[]>([])
  const [selected, setSelected] = useState<Product | null>(null)
  const [message, setMessage] = useState('')
  const add = (product: Product, quantity = 1, size = 'M', color = 'Noir') => {
    setCart(current => {
      const existing = current.find(item => item.id === product.id && item.size === size && item.color === color)
      if (existing) return current.map(item => item === existing ? { ...item, quantity: Math.min(product.stock, item.quantity + quantity) } : item)
      return [...current, { id: product.id, quantity: Math.min(product.stock, quantity), size, color }]
    })
    setMessage(`${product.name} ajouté au panier`)
  }
  return <MarketContext.Provider value={{ cart, favorites, add, toggle: id => setFavorites(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id]), update: (index, quantity) => setCart(current => current.map((item, i) => i === index ? { ...item, quantity: Math.max(1, Math.min(products.find(p => p.id === item.id)?.stock ?? 1, quantity)) } : item)), remove: index => setCart(current => current.filter((_, i) => i !== index)), openProduct: setSelected, notify: setMessage }}>
    <Header />{children}<Footer />
    <Dialog open={Boolean(selected)} onOpenChange={open => { if (!open) setSelected(null) }}><DialogContent className="max-w-3xl"><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>Collection {selected?.store} · Dakar</DialogDescription>{selected && <ProductDetail product={selected} onAdded={() => setSelected(null)} />}</DialogContent></Dialog>
    {message && <div role="status" className="fixed bottom-5 left-1/2 z-50 flex max-w-[calc(100%-28px)] -translate-x-1/2 items-center gap-3 rounded-md border border-border bg-card px-4 py-3 text-sm shadow-lg"><Check className="size-4 shrink-0 text-success"/><span>{message}</span><Button variant="ghost" size="icon" aria-label="Fermer la notification" onClick={() => setMessage('')}><X/></Button></div>}
  </MarketContext.Provider>
}
const nav = [['Accueil','/'],['Annonces','/annonces'],['Boutiques','/boutiques'],['Tout Colis','/tout-colis'],['Catégories','/categories'],['Promotions','/promotions'],['Blog','/blog'],['Contact','/contact']] as const
export function Header() {
  const { cart } = useMarket()
  const [search, setSearch] = useState('')
  const navigate = useNavigate()
  const pathname = useRouterState({ select: state => state.location.pathname })
  return <header className="bg-ink text-inverse"><div className="container-site header-top">
    <Link to="/" aria-label="TOUT∞SUITE ANNONCES — Accueil"><Brand/></Link>
    <form className="header-search" onSubmit={e => { e.preventDefault(); navigate({ to: '/boutiques', search: { q: search } }) }}><input aria-label="Recherche globale" placeholder="Rechercher des produits, boutiques, annonces..." value={search} onChange={e => setSearch(e.target.value)}/><select aria-label="Catégorie de recherche" onChange={e => setSearch(e.target.value)}><option value="">Toutes les catégories</option><option>Mode</option><option>Beauté</option><option>Électronique</option></select><Button type="submit" size="icon" className="h-full rounded-none" aria-label="Rechercher"><Search/></Button></form>
    <div className="header-actions"><Link to="/boutiques" className="header-action optional-action"><Store className="text-primary"/><span>Boutiques</span></Link><Link to="/tout-colis" className="header-action optional-action"><Package/><span>Tout Colis</span></Link><Link to="/aide" className="header-action optional-action"><CircleHelp/><span>Aide</span></Link><Button variant="header" size="icon" asChild><Link to="/favoris" aria-label="Mes favoris"><Heart/></Link></Button><Button variant="header" size="icon" className="relative" asChild><Link to="/panier" aria-label={`Mon panier, ${cart.reduce((sum, i) => sum + i.quantity, 0)} articles`}><ShoppingCart/><span className="cart-count">{cart.reduce((sum, i) => sum + i.quantity, 0)}</span></Link></Button><Link to="/mon-compte" className="flex shrink-0 items-center gap-2 text-xs"><span className="avatar"><UserRound className="size-4"/></span><span className="hidden xl:inline">Mon compte</span><ChevronDown className="hidden size-3 xl:inline"/></Link></div>
  </div><div className="nav-row"><div className="container-site nav-inner"><nav className="nav-links" aria-label="Navigation principale">{nav.map(([label,to]) => <Link key={to} to={to} className={`nav-link ${pathname === to || (to === '/boutiques' && pathname === '/') ? 'active' : ''}`}>{label}{label === 'Catégories' && <ChevronDown className="ml-1 size-3"/>}</Link>)}</nav><Button size="sm" className="create-shop-nav" asChild><Link to="/creer-boutique"><Plus className="size-3"/>Créer ma boutique</Link></Button></div></div></header>
}
export function Journey({ current = 0 }: { current?: number }) { const steps = ['Découvrir les boutiques','Visiter une boutique','Choisir un produit','Mon panier','Paiement','Suivi de commande']; const paths = ['/boutiques','/boutique/so-fab-closet','/produit/robe-elegante','/panier','/paiement','/suivi'] as const; return <div className="container-site journey">{steps.map((step,i) => <Link to={paths[i]} key={step} className={`journey-step ${current === i ? 'current' : ''}`}><span className="journey-number">{i+1}</span>{step}</Link>)}</div> }
export function Footer() { return <footer className="footer"><div className="container-site footer-inner"><div><Link to="/"><Brand/></Link><div className="footer-slogan">ACHETEZ. VENDEZ. SHOPPEZ. EXPÉDIEZ. TOUT DE SUITE.</div></div><nav className="footer-links">{[['Annonces','/annonces'],['Boutiques','/boutiques'],['Tout Colis','/tout-colis'],['Aide','/aide'],['Contact','/contact']].map(([name,to]) => <Link key={to} to={to}>{name}</Link>)}</nav></div><div className="container-site footer-bottom"><span>© 2026 TOUT∞SUITE ANNONCES. Tous droits réservés.</span><span>Dakar, Sénégal · Prix en FCFA</span><Link to="/conditions">Conditions générales & confidentialité</Link></div></footer> }
export function ShopCard({ shop }: { shop: typeof shops[number] }) { return <Link to="/boutique/$id" params={{ id: shop.id }} className="shop-card"><div className="shop-image"><img src={shop.image} alt={shop.category} width={512} height={512} loading="lazy"/></div><div className="shop-info"><h3>{shop.name}<ShieldCheck className="ml-1 inline size-3.5 text-success"/></h3><p>{shop.category}</p><div className="shop-meta"><span className="flex items-center gap-1"><MapPin/>Dakar</span><span className="flex items-center gap-1"><Star className="fill-primary text-primary"/>{shop.rating} <span className="text-muted-foreground">({shop.count})</span></span></div><span className="shop-link">Visiter la boutique <ArrowRight className="size-3"/></span></div></Link> }
export function ProductCard({ product }: { product: Product }) { const { favorites,toggle,add,openProduct } = useMarket(); return <article className="product-card"><Link to="/produit/$id" params={{ id: product.id }} className="product-image"><img src={product.image} alt={product.name} loading="lazy" width={512} height={512}/></Link>{product.discount > 0 && <span className="product-discount">−{product.discount} %</span>}<Button variant="ghost" size="icon" className="product-favorite" aria-label={`Favori : ${product.name}`} aria-pressed={favorites.includes(product.id)} onClick={() => toggle(product.id)}><Heart className={favorites.includes(product.id) ? 'fill-destructive text-destructive' : ''}/></Button><div className="product-info"><div className="product-store">{product.store}</div><h3><Link to="/produit/$id" params={{ id: product.id }}>{product.name}</Link></h3><div><span className="price">{formatMoney(product.price)}</span>{product.oldPrice > 0 && <span className="old-price">{formatMoney(product.oldPrice)}</span>}</div><div className="product-bottom"><span className="product-rating"><Star/>{product.rating} <span className="text-muted-foreground">· En stock</span></span><Button variant="dark" size="icon" className="size-7 rounded" aria-label={`Ajouter ${product.name} au panier`} onClick={() => product.category === 'Mode' && product.id.includes('robe') ? openProduct(product) : add(product)}><ShoppingCart className="size-3.5"/></Button></div></div></article> }
export function ProductDetail({ product, onAdded }: { product: Product; onAdded?: () => void }) { const { add,toggle,favorites } = useMarket(); const [size,setSize] = useState('M'); const [color,setColor] = useState('Noir'); const [quantity,setQuantity] = useState(1); return <div className="detail-grid"><img className="detail-image" src={product.image} alt={product.name} width={512} height={512}/><div><p className="mb-3 flex items-center gap-1 text-xs"><Star className="size-3 fill-primary text-primary"/>{product.rating} · {product.store}</p><div className="mb-4"><span className="price text-xl">{formatMoney(product.price)}</span>{product.oldPrice > 0 && <span className="old-price">{formatMoney(product.oldPrice)}</span>}</div><p className="mb-5 text-sm leading-relaxed text-muted-foreground">{product.name === 'Robe élégante' ? 'Robe élégante en tissu de qualité, parfaite pour vos événements, sorties et occasions spéciales.' : `${product.name}, sélection de la boutique ${product.store}.`}</p><div className="choice-label">Couleur : {color}</div><div className="choice-row">{['Noir','Doré','Blanc'].map(value => <Button variant="ghost" key={value} className={`swatch ${value.toLowerCase()} ${value === color ? 'active' : ''}`} size="icon" aria-label={`Couleur ${value}`} aria-pressed={value === color} onClick={() => setColor(value)}/>)}</div>{product.id.includes('robe') && <><div className="choice-label">Taille</div><div className="choice-row">{['S','M','L','XL'].map(value => <Button size="sm" variant={size === value ? 'default' : 'outline'} key={value} aria-pressed={size === value} onClick={() => setSize(value)}>{value}</Button>)}</div></>}<div className="choice-label mb-2">Quantité</div><div className="quantity mb-5"><Button variant="ghost" size="icon" aria-label="Réduire la quantité" disabled={quantity === 1} onClick={() => setQuantity(q => Math.max(1,q-1))}><Minus/></Button><span>{quantity}</span><Button variant="ghost" size="icon" aria-label="Augmenter la quantité" disabled={quantity >= product.stock} onClick={() => setQuantity(q => Math.min(product.stock,q+1))}><Plus/></Button></div><Button className="w-full" onClick={() => { add(product,quantity,size,color); onAdded?.() }}><ShoppingCart/>Ajouter au panier</Button><Button variant="outline" className="mt-2 w-full" onClick={() => toggle(product.id)}><Heart className={favorites.includes(product.id) ? 'fill-destructive text-destructive' : ''}/>{favorites.includes(product.id) ? 'Retirer des favoris' : 'Ajouter aux favoris'}</Button><p className="mt-4 flex items-center gap-1 text-xs text-success"><Check className="size-3"/>En stock · {product.stock} disponibles</p><p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><Package className="size-3"/>Livraison Dakar : 2 000 FCFA</p></div></div> }
export function CartView() { const { cart,update,remove } = useMarket(); const totals = cartTotals(cart); return cart.length ? <div className="grid gap-8 md:grid-cols-[minmax(0,1fr)_320px]"><div>{cart.map((item,index) => { const product = products.find(p => p.id === item.id); if (!product) return null; return <div className="cart-row" key={`${item.id}-${index}`}><img src={product.image} alt={product.name}/><div><Link to="/produit/$id" params={{ id: product.id }} className="text-sm font-semibold">{product.name}</Link><p className="my-1 text-xs text-muted-foreground">{product.store} · {item.size} · {item.color}</p><span className="price">{formatMoney(product.price)}</span><div className="quantity mt-2"><Button variant="ghost" size="icon" className="size-7" aria-label={`Réduire ${product.name}`} disabled={item.quantity === 1} onClick={() => update(index,item.quantity-1)}><Minus/></Button><span>{item.quantity}</span><Button variant="ghost" size="icon" className="size-7" aria-label={`Augmenter ${product.name}`} disabled={item.quantity >= product.stock} onClick={() => update(index,item.quantity+1)}><Plus/></Button></div></div><div className="text-right"><Button size="icon" variant="ghost" aria-label={`Supprimer ${product.name}`} onClick={() => remove(index)}><Trash2 className="text-muted-foreground"/></Button><p className="mt-3 text-sm font-semibold">{formatMoney(product.price*item.quantity)}</p></div></div>})}<Button variant="outline" className="mt-6" asChild><Link to="/boutiques">Continuer mes achats</Link></Button></div><aside className="border-l-0 border-border md:border-l md:pl-7"><h2 className="mb-5 text-2xl">Résumé du panier</h2><div className="total-row"><span>Sous-total</span><span>{formatMoney(totals.subtotal)}</span></div><div className="total-row text-muted-foreground"><span>Livraison Dakar</span><span>{formatMoney(totals.delivery)}</span></div><div className="total-row mt-3 border-t border-border pt-4 font-bold"><span>Total</span><span data-testid="cart-total">{formatMoney(totals.total)}</span></div><Button className="mt-5 w-full" asChild><Link to="/paiement">Passer la commande <ArrowRight/></Link></Button><p className="mt-3 text-xs text-muted-foreground">Panier de démonstration. Aucun paiement ne sera prélevé.</p></aside></div> : <div className="empty-state"><ShoppingCart className="mx-auto mb-5 size-12"/><h2 className="mb-2 text-2xl text-foreground">Votre panier est vide</h2><p className="mb-5 text-sm">Découvrez les sélections de nos boutiques.</p><Button asChild><Link to="/boutiques">Découvrir les produits <ArrowRight/></Link></Button></div> }